### ISSUE TITLE
Documentation Request: Windows CLI/batch file use

### ISSUE THREAD

**Issue by JpTiger** [honsiorovskyi/open-url-in-container#12]
Thanks for making this, this looks great! What I'd love to be able to do with it is make a batch file so that when I run a script, two windows are opened with tabs loading to specific pages in specific containers. I've tried using the commands you've listed here (without the script) but I'm guessing they're BASH rather than windows' cmd, because they don't seem to work as described on my machine. It's entirely possible that I'm doing something simple and dumb that's causing this failure, but if not, could you provide some guidance for us Windows users?

**Comment by honsiorovskyi** [comment]
Hey @JpTiger, thank you for you comment!

I will consider adding a bat/powershell/whatever version of the script to the repository, but currently I'm a bit short on time, and Windows is not my main platform, so I can't promise anything soon.

Another thing is that currently the extension doesn't allow opening tabs in the new window. Currently it opens tabs in what Firefox considers to be the current window (probably the last opened/focused window, I might be wrong, though). I want to implement this option in the future too.

Currently I can propose you running the command using something like this:

```
C:\Program Files\Mozilla Firefox\firefox.exe 'ext+container:name=MyContainer&url=https://mozilla.org'
```

Sadly, I can't verify it because I don't have a Windows computer at hand, but if it doesn't work, please also try changing the single quotes to double quotes, or simply removing them.

**Comment by JpTiger** [comment]
Double quotes seems to do the trick! I had to alter other parts of the syntax slightly. Here's what worked for me:

`C:\"Program Files"\"Mozilla Firefox"\firefox.exe "ext+container:name=MyContainer&"url=https://mozilla.org`

Note that if your container has any special characters in it, it's a good idea to wrap the container name in double quotes as well.

Works fine in batch files, too, just write "start" in front of the command.

Thanks for the help!
