### ISSUE TITLE
Does this add-on make containers vulnerable to correlation?

### ISSUE THREAD

**Issue by Roy-Orbison** [honsiorovskyi/open-url-in-container#46]
E.g. does loading resources via the extension scheme bypass the normal isolation? E.g.:

``` html
<img src="ext+container:name=Facebook&url=https://facebook.com/we-have-you-by-the-short-and-curlies-now/id-6d6866633833376e67326668386d6f33346f.jpg">
```

**Comment by MichaelTunnell** [comment]
I don't know exactly what you mean for this but I think you are asking if the Facebook Container will still take control even if the container put in the protocol is not Facebook?

If that's the case, then the Facebook Container extension still takes control regardless of the container name you put in the protocol.

So Facebook Container will always take priority over all Facebook related domains regardless what you put in the protocol which to me is good news. :sunglasses:

**Comment by Roy-Orbison** [comment]
Facebook was just an example. Firefox comes with a number of default container names. My question is whether any site with a vested interest in tracking users could include "images" or other resources via script, hidden div, etc. with a URL that identifies this user + container, then see if when the request is sent via another container it gets sent with the other container's cookies. This would correlate two IDs and defeat the purpose of containers by identifying the user across the boundary.

**Comment by MichaelTunnell** [comment]
Facebook Container is a different type of extension not a regular container and a lot of the other site containers were built as a fork of the Facebook Container from Mozilla. If you look in the description of the container you are asking about and it says forked from the Facebook Container then it too will act the same way forcing priority to that container.

Even though the Facebook Container is a separate extension it is still directly connected to main container extension. So there is no way to make a Facebook container in addition to the Facebook Container extension because that extension will automatically create one anyway so there wouldnt be any conflict with putting Facebook in the name of the protocol for this extension . . . in fact in theory you shouldn't even need to use this protocol at all in order to use those extensions because they are meant to force priority regardless.

**Comment by Roy-Orbison** [comment]
As I said earlier, Facebook was just an example. I'm not talking about Facebook, specifically, nor the Facebook Container extension, I'm talking about *any* cross-container request. Instead imagine this request from the default **Work** container to the **Personal** one:
``` html
<img src="ext+container:name=Personal&amp;url=https://example.com/cross-container-check/to-container-Personal/unique-identifier-from-this-container.gif">
```

**Comment by rafaelgssa** [comment]
I tried making a `fetch` request and got this:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ext+container:name=[redacted]&url=[redacted]. (Reason: CORS request not http).
```

So I don't think it's possible to make such CORS requests.

**Comment by honsiorovskyi** [comment]
Hey @Roy-Orbison, thanks for rising this concern. I did some tests and Firefox does block resource requests for these custom protocols indeed (see [a test page](https://github.com/honsiorovskyi/open-url-in-container/blob/master/tests/testdata/example-links.html) as an example), but websites still can trick people into clicking links which open in different containers, and therefore perform tracking in that way.

I'll try to find some mitigation mechanism which doesn't affect UX a lot for this.

**Comment by honsiorovskyi** [comment]
Hi @Roy-Orbison, thanks again for rising this issue.

I've just pushed to master a preview build of a new version featuring links signing which should address this issue. Please feel free to try out [the new build](https://github.com/honsiorovskyi/open-url-in-container/releases/tag/2.0.0alpha5), review the new [README](https://github.com/honsiorovskyi/open-url-in-container/blob/master/README.md) file and the code itself.

I'm closing the issue now, but feel free to re-open it if needed.
