### ISSUE TITLE
Error creating new tab: Error: Type error for parameter createProperties (Unexpected property "openInReaderMode") for tabs.create..

### ISSUE THREAD

**Issue by br4nnigan** [honsiorovskyi/open-url-in-container#77]
I use this as a bookmarks url using the standard Youtube container:

ext+container:name=Youtube&url=https://www.youtube.com/feed/subscriptions

Result:

> Open external links in a container. Or not.
> 
> We are unable to open the URL you requested. This could be due to an internal problem or some mistakes in your link. Please check the correctness of your link and try again. If you think there's a problem with an extension, please let us know.
> 
> The error we received is following:
> 
> Error creating new tab: Error: Type error for parameter createProperties (Unexpected property "openInReaderMode") for tabs.create..

And here's the kicker, I'm on Waterfox Classic 2020.04 (latest build). It would be bomb it this bug could be considered anyway. We all like FOSS, _right?_

**Comment by honsiorovskyi** [comment]
Hey @br4nnigan, thank you for the bug report! I just fixed this issue and pushed it to master, it will be available in the Mozilla Addons Store shortly. However, there's one more issue with both Waterfox Classic and Waterfox Current: for some reason both of them allow loading of the containerized iframes, which [has been disabled in the mainstream Firefox since version 67](https://www.fxsitecompat.dev/en-CA/docs/2019/loading-of-external-protocol-url-in-iframe-is-now-blocked/).

I will try to develop a fix for [this issue](https://github.com/honsiorovskyi/open-url-in-container/issues/46) which would probably cover the iframe case as well, but I can't promise the very best user experience for Waterfox. Also, keep in mind that until the fix is deployed and unless you use some external tool like uMatrix to block iframes, websites potentially [might be able to track you like this (but with iframes)](https://github.com/honsiorovskyi/open-url-in-container/issues/46#issuecomment-591225314).

**Comment by br4nnigan** [comment]
Wow, you're awesome, it works! You should add a donation link somewhere
